# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/windows/Users/ibrah/2024-group-17

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/windows/Users/ibrah/2024-group-17/cpp-opencv

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/windows/Users/ibrah/2024-group-17/cpp-opencv/CMakeFiles /mnt/windows/Users/ibrah/2024-group-17/cpp-opencv//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/windows/Users/ibrah/2024-group-17/cpp-opencv/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

#=============================================================================
# Target rules for targets named coverage

# Build rule for target.
coverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coverage
.PHONY : coverage

# fast build rule for target.
coverage/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coverage.dir/build.make CMakeFiles/coverage.dir/build
.PHONY : coverage/fast

#=============================================================================
# Target rules for targets named helloworld-Runner

# Build rule for target.
helloworld-Runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 helloworld-Runner
.PHONY : helloworld-Runner

# fast build rule for target.
helloworld-Runner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/build
.PHONY : helloworld-Runner/fast

src/PrimeChecker.o: src/PrimeChecker.cpp.o
.PHONY : src/PrimeChecker.o

# target to build an object file
src/PrimeChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/PrimeChecker.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/src/PrimeChecker.cpp.o
.PHONY : src/PrimeChecker.cpp.o

src/PrimeChecker.i: src/PrimeChecker.cpp.i
.PHONY : src/PrimeChecker.i

# target to preprocess a source file
src/PrimeChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/PrimeChecker.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/src/PrimeChecker.cpp.i
.PHONY : src/PrimeChecker.cpp.i

src/PrimeChecker.s: src/PrimeChecker.cpp.s
.PHONY : src/PrimeChecker.s

# target to generate assembly for a file
src/PrimeChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/PrimeChecker.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/src/PrimeChecker.cpp.s
.PHONY : src/PrimeChecker.cpp.s

src/helloworld.o: src/helloworld.cpp.o
.PHONY : src/helloworld.o

# target to build an object file
src/helloworld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/helloworld.cpp.o
.PHONY : src/helloworld.cpp.o

src/helloworld.i: src/helloworld.cpp.i
.PHONY : src/helloworld.i

# target to preprocess a source file
src/helloworld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/helloworld.cpp.i
.PHONY : src/helloworld.cpp.i

src/helloworld.s: src/helloworld.cpp.s
.PHONY : src/helloworld.s

# target to generate assembly for a file
src/helloworld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/src/helloworld.cpp.s
.PHONY : src/helloworld.cpp.s

test/TestPrimeChecker.o: test/TestPrimeChecker.cpp.o
.PHONY : test/TestPrimeChecker.o

# target to build an object file
test/TestPrimeChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/test/TestPrimeChecker.cpp.o
.PHONY : test/TestPrimeChecker.cpp.o

test/TestPrimeChecker.i: test/TestPrimeChecker.cpp.i
.PHONY : test/TestPrimeChecker.i

# target to preprocess a source file
test/TestPrimeChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/test/TestPrimeChecker.cpp.i
.PHONY : test/TestPrimeChecker.cpp.i

test/TestPrimeChecker.s: test/TestPrimeChecker.cpp.s
.PHONY : test/TestPrimeChecker.s

# target to generate assembly for a file
test/TestPrimeChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/helloworld-Runner.dir/build.make CMakeFiles/helloworld-Runner.dir/test/TestPrimeChecker.cpp.s
.PHONY : test/TestPrimeChecker.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... coverage"
	@echo "... helloworld"
	@echo "... helloworld-Runner"
	@echo "... src/PrimeChecker.o"
	@echo "... src/PrimeChecker.i"
	@echo "... src/PrimeChecker.s"
	@echo "... src/helloworld.o"
	@echo "... src/helloworld.i"
	@echo "... src/helloworld.s"
	@echo "... test/TestPrimeChecker.o"
	@echo "... test/TestPrimeChecker.i"
	@echo "... test/TestPrimeChecker.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

